import type { MetadataRoute } from "next"

const SITE_URL = "https://2pt.ai"

/**
 * robots.txt — generated by Next.js, served at /robots.txt.
 *
 * Allow everything (the page is a public marketing surface). Block the
 * Next.js internals + opengraph image route from being indexed directly.
 *
 * Explicitly allows the major AI/search crawlers (GPTBot, ClaudeBot,
 * PerplexityBot, Google-Extended) — they default to allowed unless robots
 * disallow, but being explicit makes intent clear.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/", "/opengraph-image"],
      },
      // AI search engines — explicitly allowed
      { userAgent: "GPTBot", allow: "/" },
      { userAgent: "ChatGPT-User", allow: "/" },
      { userAgent: "ClaudeBot", allow: "/" },
      { userAgent: "Claude-Web", allow: "/" },
      { userAgent: "anthropic-ai", allow: "/" },
      { userAgent: "PerplexityBot", allow: "/" },
      { userAgent: "Google-Extended", allow: "/" },
      { userAgent: "Applebot-Extended", allow: "/" },
      { userAgent: "Bytespider", allow: "/" },
      { userAgent: "CCBot", allow: "/" },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  }
}
