import type { MetadataRoute } from "next"

const SITE_URL = "https://2pt.ai"

/**
 * sitemap.xml — generated by Next.js at build time, served at /sitemap.xml.
 *
 * Routes:
 *  • /          — homepage (Organization, ProfessionalService, FAQ, HowTo,
 *                 LocalBusiness × 2, Person, Article, DefinedTermSet)
 *  • /faq       — 29-question FAQ corpus (FAQPage)
 *  • /glossary  — 14-term definition page (DefinedTermSet)
 *
 * Each route is included with a priority and changeFrequency that reflects
 * how often the content changes. The homepage is the canonical entry point;
 * /faq and /glossary are evergreen reference surfaces.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return [
    {
      url: SITE_URL,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${SITE_URL}/faq`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${SITE_URL}/glossary`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.9,
    },
  ]
}
