import type { MetadataRoute } from "next"

const SITE_URL = "https://2pt.ai"

/**
 * sitemap.xml — generated by Next.js at build time, served at /sitemap.xml.
 *
 * Single-page site for now (root with in-page anchors). When additional
 * routes ship (case studies, products, blog), add them here with sensible
 * lastModified, changeFrequency and priority values.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()
  return [
    {
      url: SITE_URL,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1.0,
    },
  ]
}
